### ISSUE TITLE
Are there any plans to update jSerialComm to the latest version (2.3.0)?

### ISSUE THREAD

**Issue by dvk2018** [steveohara/j2mod#90]

**Comment by dvk2018** [comment]
Also, is it a convenient way for this project to update the jSerialComm version every time j2mod has been released?

**Comment by steveohara** [comment]
There is now!
I always want to keep closely aligned with JSerialComm so I will update and test j2mod with 2.3.0 next week when I'm back in the UK

**Comment by steveohara** [comment]
I've updated to V2.3.0 - there is a possibility that there is an issue with this version of the comms library because I had to alter the blocking strategy on reads to make it work.
If you could try this snapshot version out I would appreciate some feedback
https://oss.sonatype.org/content/repositories/snapshots/com/ghgande/j2mod/2.5.3-SNAPSHOT/j2mod-2.5.3-20181216.230213-3-sources.jar

**Comment by steveohara** [comment]
Many thanks

**Comment by dvk2018** [comment]
Hi @steveohara,
When are you going to release 2.53 version?

**Comment by steveohara** [comment]
Just been released - if you wait an hour or so, it will appear on Maven Central
